import {
  AlertTriangle,
  ArrowRight,
  Check,
  ChevronLeft,
  ChevronRight,
  CircuitBoardIcon,
  Command,
  CreditCard,
  File,
  FileText,
  HelpCircle,
  HousePlus,
  Image,
  Laptop,
  LayoutDashboardIcon,
  Loader2,
  LogIn,
  Moon,
  MoreVertical,
  Pizza,
  Plus,
  Settings,
  SquareLibrary,
  SunMedium,
  Trash,
  User,
  User2Icon,
  UserX2Icon,
  X,
} from 'lucide-react'

// Update the IconSet type to match lucide-react's type
type IconSet = {
  [key: string]: React.ComponentType<React.SVGProps<SVGSVGElement>>
}

export const Icons: IconSet = {
  dashboard: LayoutDashboardIcon,
  logo: Command,
  login: LogIn,
  close: X,
  profile: User2Icon,
  spinner: Loader2,
  kanban: CircuitBoardIcon,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  trash: Trash,
  employee: UserX2Icon,
  post: FileText,
  page: File,
  media: Image,
  settings: Settings,
  billing: CreditCard,
  ellipsis: MoreVertical,
  add: Plus,
  warning: AlertTriangle,
  user: User,
  arrowRight: ArrowRight,
  help: HelpCircle,
  pizza: Pizza,
  sun: SunMedium,
  moon: Moon,
  laptop: Laptop,
  house: HousePlus,
  reservation: SquareLibrary,
  check: Check,
}
