//import Header from "@src/components/header";
//import Footer from "@src/components/footer";
import { Metadata } from "next";
import { Providers } from "@src/components/ThemeProvider";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html suppressHydrationWarning lang="en">
			<body className="bg-black dark:bg-slate-600">
				<Providers>
					{/* <Header /> */}
					<main> {children} </main>
					{/* <Footer /> */}
				</Providers>
			</body>
		</html>
	);
}
