name: Build and deploy image to AWS Production environment

on:
  push:
    branches:
      - master
      
permissions:
  id-token: write
  contents: read

jobs:
  build-and-push-app:
    name: Build and push Mirama APP image to ECR
    uses: ./.github/workflows/build-and-push-image.yaml
    with:
      github-environment: prod
      ecr-repository: mirama-prod-application-repository
      image-tag: "latest"
      dockerfile-path: Dockerfile
      aws-account-id: "465852549019"
        
